#!/bin/bash
#!/usr/bin/env bash

set -o errexit
trap 'echo "Aborting due to errexit on line $LINENO. Exit code: $?" >&2' ERR
set -o errtrace
set -o pipefail
DEFAULT_IFS="${IFS}"
SAFER_IFS=$'\n\t'
IFS="${SAFER_IFS}"
_ME=$(basename "${0}")

_print_help() {
  cat <<HEREDOC
                 __               .__
__  _  _______ _/  |_  ___________|  |   ____   ____ ______
\\ \\/ \\/ /\\__  \\\\   __\\/ __ \\_  __ \\  |  /  _ \\ /  _ \\\\____ \\
 \\     /  / __ \\|  | \\  ___/|  | \\/  |_(  <_> |  <_> )  |_> >
  \\/\\_/  (____  /__|  \\___  >__|  |____/\\____/ \\____/|   __/
              \\/          \\/                         |__|
The Embedded C++ code base builder
HEREDOC
}

BUILD_DIR=cmake-build-debug

_build() {
    _glsl_compile
    mkdir -p $BUILD_DIR
    cd $BUILD_DIR
    cmake ..
    make -j10
}

_clean() {
    rm $(pwd)/include/*.glsl
    cd $BUILD_DIR
    make clean -j10
}

_run() {
    cd $BUILD_DIR
    ./shadertoy
}

_setup() {
    sudo apt-get install libsfml-dev
}

_glsl_compile() {
    mkdir -p $(pwd)/include
    cd $(pwd)/glsl
    find ./ -type f -name "*.glsl" \
        -exec xxd -i {} ../include/{} \;
    cd ../
}

_simple() {
    root_dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
    root_dir_name=$(basename "$root_dir")
    cd "$root_dir"

    if [ "$1" == 'build' ] ; then
        echo "Building project"
        _build
    elif [ "$1" == 'clean' ] ; then
        echo "Cleaning project"
        _clean
    elif [ "$1" == 'run' ] ; then
        _run
    elif [ "$1" == 'setup' ] ; then
        echo "Setting up environment for Linux"
        _setup
    else
        _print_help
    fi
}

_main() {
  # Avoid complex option parsing when only one program option is expected.
  if [[ "${1:-}" =~ ^-h|--help$  ]] || [ $# -lt "1" ]
  then
    _print_help
  else
    _simple "$@"
  fi
}

_main "$@"
